[pytest]
DJANGO_SETTINGS_MODULE = lib_ms.settings
python_files = tests.py test_*.py *_tests.py
testpaths = tests
addopts = 
    --strict-markers
    --disable-warnings
    --tb=short
    -v

[coverage:run]
source = .
omit =
    */tests/*
    */migrations/*
    manage.py
    setup.py
