# Generated by Django 5.0.6 on 2025-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category_book_external_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
