# Generated by Django 5.0.6 on 2025-11-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PICKED_UP', 'Picked Up'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
