# Generated by Django 5.0.6 on 2025-12-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
