# Generated by Django 5.0.6 on 2025-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
