# Generated by Django 5.0.6 on 2025-11-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitycomment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycomment',
            name='rating',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
