# Generated by Django 5.2.8 on 2025-11-26 13:09

import django.db.models.deletion
from django.db import migrations, models


def assign_books(apps, schema_editor):
    Post = apps.get_model('community', 'CommunityPost')
    Book = apps.get_model('books', 'Book')
    for post in Post.objects.filter(book__isnull=True).exclude(book_title=''):
        book = Book.objects.filter(title__iexact=post.book_title).first()
        if book:
            post.book_id = book.id
            post.save(update_fields=['book'])


def unassign_books(apps, schema_editor):
    Post = apps.get_model('community', 'CommunityPost')
    Post.objects.update(book=None)


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_page_count_alter_book_stock'),
        ('community', '0003_remove_communitycomment_rating_communitypost_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='books.book'),
        ),
        migrations.RunPython(assign_books, unassign_books),
    ]
